[package]
name = "holo-db"
version = "0.1.0"
edition = "2021"
description = "Compilation artifact database abstraction for holo"
license = "MIT"
publish = false

[dependencies]
holo-base = { path = "../base" }
