[package]
name = "holo-interpreter"
version = "0.1.0"
edition = "2021"
description = "Interpreter for running minimal holo tests"
license = "MIT"
publish = false

[dependencies]
holo-base = { path = "../base" }
holo-ast = { path = "../ast" }
holo-ir = { path = "../ir" }
tracing = "0.1"
