[workspace]
resolver = "2"
members = [
    "ast",
    "base",
    "cli",
    "core",
    "deck",
    "db",
    "fs",
    "interpreter",
    "ipc",
    "lexer",
    "parser",
    "query",
    "typechecker",
]
default-members = ["cli"]
